---
version: 2
updates:
- package-ecosystem: pip
  directory: "/api"
  versioning-strategy: increase-if-necessary
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  groups:
    deps:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
  commit-message:
    prefix: "chore(api)"
- package-ecosystem: npm
  directory: "/frontend"
  versioning-strategy: increase-if-necessary
  schedule:
    interval: monthly
  open-pull-requests-limit: 1
  groups:
    deps:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "major"
        - "minor"
        - "patch"
  commit-message:
    prefix: "chore(frontend)"
  labels:
    - "dependencies"
    - "javascript"
    - "testing needed"
