version: 2
updates:
- package-ecosystem: pip
  directory: "/api/requirements"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
