const webpack = require('webpack');
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const DEFAULT_HOST = 'localhost';
const DEFAULT_PORT = 8010;
const host = process.env.HOST || DEFAULT_HOST;
const port = process.env.PORT || DEFAULT_PORT;
const SHIPIT_PUBLIC_API_URL =
  process.env.SHIPIT_PUBLIC_API_URL || 'https://localhost:8016';
const SHIPIT_API_URL = process.env.SHIPIT_API_URL || 'https://localhost:8015';
const FRONTEND_TASKCLUSTER_ROOT_URL =
  process.env.FRONTEND_TASKCLUSTER_ROOT_URL ||
  'https://firefox-ci-tc.services.mozilla.com';
const DEPLOYMENT_BRANCH = process.env.DEPLOYMENT_BRANCH || 'development';
const connectSrc = [
  'https://hg.mozilla.org',
  'https://hg-edge.mozilla.org',
  'https://auth.mozilla.auth0.com',
  SHIPIT_API_URL,
  SHIPIT_PUBLIC_API_URL,
  FRONTEND_TASKCLUSTER_ROOT_URL,
  "'self'",
].join(' ');

// DO NOT USE DEVTOOLS THAT RELY ON EVAL IN PRODUCTION
// These include tools such as 'cheap-module-eval-source-map'
module.exports = (_, { mode }) => {
  return {
    devtool: mode === 'production' ? false : 'eval-cheap-module-source-map',
    target: 'web',
    context: __dirname,
    stats: {
      children: false,
      entrypoints: false,
      modules: false,
    },
    output: {
      path: `${__dirname}/build`,
      clean: true,
      publicPath: '/',
      filename: 'assets/[name].[contenthash:8].js',
      globalObject: 'this',
    },
    resolve: {
      alias: {
        'react-native': 'react-native-web',
      },
      extensions: [
        '.web.jsx',
        '.web.js',
        '.wasm',
        '.mjs',
        '.jsx',
        '.js',
        '.json',
      ],
      fallback: {
        Buffer: false,
        fs: false,
        tls: false,
        assert: 'assert',
      },
    },
    devServer: {
      host,
      port,
      server: 'https',
      historyApiFallback: {
        disableDotRule: true,
      },
      headers: {
        'Content-Security-Policy':
          `connect-src ${connectSrc}; ` +
          "default-src https://auth.mozilla.auth0.com 'none'; " +
          "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.auth0.com; " +
          "img-src 'self' https://*.gravatar.com https://i1.wp.com data:; " +
          "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; " + // Styles are generated by JS, thus require 'unsafe-inline'
          'font-src https://fonts.gstatic.com; ' +
          "frame-ancestors 'none'; " +
          "base-uri 'none'; " +
          "form-action 'none'",
        'X-Frame-Options': 'SAMEORIGIN',
        'X-Content-Type-Options': 'nosniff',
        'X-XSS-Protection': '1; mode=block',
        'Referrer-Policy': 'no-referrer',
        'Strict-Transport-Security':
          'max-age=31536000; includeSubDomains; always;',
      },
    },
    module: {
      rules: [
        {
          test: /\.m?js/,
          resolve: {
            fullySpecified: false,
          },
        },
        {
          test: /\.(js|jsx)$/,
          include: [`${__dirname}/src`, `${__dirname}/test`],
          use: [
            {
              loader: 'babel-loader',
              options: {
                cacheDirectory: true,
                babelrc: false,
                configFile: false,
                presets: [
                  [
                    '@babel/preset-env',
                    {
                      debug: false,
                      useBuiltIns: false,
                      shippedProposals: true,
                      targets: {
                        browsers: [
                          'last 2 Chrome versions',
                          'last 2 Firefox versions',
                          'last 2 Edge versions',
                          'last 2 Opera versions',
                          'last 2 Safari versions',
                          'last 2 iOS versions',
                        ],
                      },
                    },
                  ],
                  [
                    '@babel/preset-react',
                    {
                      development: mode === 'development',
                      useSpread: true,
                    },
                  ],
                ],
                plugins: [
                  '@babel/plugin-syntax-dynamic-import',
                  [
                    'transform-react-remove-prop-types',
                    {
                      removeImport: true,
                    },
                  ],
                  ...(mode === 'development' ? ['react-refresh/babel'] : []),
                ],
              },
            },
          ],
        },
        {
          oneOf: [
            {
              test: /\.module\.css$/,
              use: [
                {
                  loader: MiniCssExtractPlugin.loader,
                  options: {
                    esModule: true,
                  },
                },
                {
                  loader: 'css-loader',
                  options: {
                    importLoaders: 0,
                    modules: true,
                  },
                },
              ],
            },
            {
              test: /\.css$/,
              use: [
                {
                  loader: MiniCssExtractPlugin.loader,
                  options: {
                    esModule: true,
                  },
                },
                {
                  loader: 'css-loader',
                  options: {
                    importLoaders: 0,
                  },
                },
              ],
            },
          ],
        },
        {
          test: /\.(eot|ttf|woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
          type: 'asset/resource',
        },
        {
          test: /\.(ico|png|jpg|jpeg|gif|svg|webp)(\?v=\d+\.\d+\.\d+)?$/,
          type: 'asset/resource',
        },
        {
          test: /.worker\.js$/,
          use: [
            {
              loader: 'worker-loader',
            },
          ],
        },
      ],
    },
    optimization: {
      minimize: true,
      splitChunks: {
        chunks: 'all',
        maxInitialRequests: 5,
        name: false,
      },
      runtimeChunk: 'single',
    },
    plugins: [
      new webpack.ProvidePlugin({ process: 'process/browser' }),
      new webpack.EnvironmentPlugin({
        HOST: host,
        PORT: port,
        SHIPIT_API_URL,
        SHIPIT_PUBLIC_API_URL,
        DEPLOYMENT_BRANCH,
      }),
      new HtmlWebpackPlugin({
        template: 'src/index.html',
        templateContent: false,
        filename: 'index.html',
        publicPath: 'auto',
        hash: false,
        inject: 'body',
        scriptLoading: 'blocking',
        compile: true,
        favicon: `${__dirname}/src/images/shipit.png`,
        minify: 'auto',
        cache: true,
        showErrors: true,
        chunks: ['index'],
        excludeChunks: [],
        chunksSortMode: 'auto',
        meta: {
          viewport: 'width=device-width, initial-scale=1',
        },
        base: false,
        title: 'Webpack App',
        xhtml: false,
        appMountId: 'root',
        lang: 'en',
      }),
      new MiniCssExtractPlugin({
        filename: 'assets/[name].[contenthash:8].css',
        ignoreOrder: false,
        chunkFilename: 'assets/[name].[contenthash:8].css',
      }),
      ...(mode === 'development' ? [new ReactRefreshWebpackPlugin()] : []),
    ],
    entry: {
      index: [`${__dirname}/src/index`],
    },
  };
};
