repos:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/repo.yaml
  projects:
    - /
docker-compose:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/docker-compose.yaml
  projects:
    - /
apps:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/python-app.yaml
  projects:
    - /api
