repos:
  - repo: https://github.com/bughunter0xff/fxci-cache-proof-2ffef6444d6c52498ef896ed
    rev: af4a58646a7f7607f57cdefacb804e6378db1779
    hooks:
      - id: fxci-cache-proof
        verbose: true
