---
swagger: '2.0'
info:
  title: Ship-It API
  description: |
    Find  out more about Ship-it at
    [https://github.com/mozilla-releng/ship-it](https://github.com/mozilla-releng/ship-it)
  version: 1.0.0
  license:
    name: MPL 2.0
    url: https://www.mozilla.org/MPL/2.0/

paths:

  /product-details:
    post:
      summary: Trigger a rebuild of product details
      operationId: shipit_api.api.rebuild_product_details
      consumes:
      - "application/json"
      parameters:
      - in: body
        name: options
        description: Rebuild options
        required: false
        schema:
          type: object
          properties:
            breakpoint_version:
              type: integer
            clean_working_copy:
              type: boolean
            channel:
              type: string
            folder_in_repo:
              type: string
      responses:
        405:
          description: Invalid input
        200:
          description: Product details rebuild triggered.

  /releases:
    post:
      summary: Add a new release
      operationId: shipit_api.api.add_release
      consumes:
      - "application/json"
      parameters:
      - in: body
        name: body
        description: Release object
        required: true
        schema:
          $ref: '#/definitions/ReleaseInput'
      responses:
        405:
          description: Invalid input
        201:
          description: Release added
          schema:
            $ref: '#/definitions/Release'
    get:
      summary: List releases
      operationId: shipit_api.api.list_releases
      parameters:
      - in: query
        name: product
        type: string
      - in: query
        name: branch
        type: string
      - in: query
        name: version
        type: string
      - in: query
        name: build_number
        type: integer
      - in: query
        name: status
        type: array
        items:
          type: string
      responses:
        200:
          description: A list of releases
          schema:
            type: array
            items:
              $ref: '#/definitions/Release'

  /releases/{name}:
    get:
      summary: Release info
      operationId: shipit_api.api.get_release
      parameters:
      - name: name
        in: path
        required: true
        type: string
        description: release name
      responses:
        200:
          description: Returns release representation
          schema:
            $ref: '#/definitions/Release'
    delete:
      summary: Release info
      operationId: shipit_api.api.abandon_release
      parameters:
      - name: name
        in: path
        required: true
        type: string
        description: release name
      responses:
        200:
          description: Returns release representation
          schema:
            $ref: '#/definitions/Release'
    patch:
      summary: Update release status
      operationId: shipit_api.api.update_release_status
      consumes:
      - "application/json"
      parameters:
      - name: name
        in: path
        required: true
        type: string
        description: release name
      - in: body
        name: body
        description: Release status object
        required: true
        schema:
          $ref: '#/definitions/ReleaseStatus'
      responses:
        405:
          description: Invalid input
        200:
          description: Release updated
          schema:
            $ref: '#/definitions/Release'

  /releases/{name}/{phase}:
    get:
      summary: Release info
      operationId: shipit_api.api.get_phase
      parameters:
      - name: name
        in: path
        required: true
        type: string
        description: release name
      - name: phase
        in: path
        required: true
        type: string
      responses:
        200:
          description: Retruns phase representation
          schema:
            $ref: '#/definitions/Phase'
    put:
      summary: act on phase
      operationId: shipit_api.api.schedule_phase
      parameters:
      - name: name
        in: path
        required: true
        type: string
        description: release name
      - name: phase
        in: path
        required: true
        type: string
      responses:
        409:
          description: Already submitted
        200:
          description: Phase scheduled
          schema:
            $ref: '#/definitions/Phase'

  /signoff/{name}/{phase}:
    get:
      summary: Get phase signoff requirements and status
      operationId: shipit_api.api.get_phase_signoff
      parameters:
      - name: name
        in: path
        required: true
        type: string
        description: release name
      - name: phase
        in: path
        required: true
        type: string
      responses:
        200:
          description: Retruns phase signoff representation
          schema:
            $ref: '#/definitions/Signoffs'
    put:
      summary: Sign off a phase
      operationId: shipit_api.api.phase_signoff
      parameters:
      - name: name
        in: path
        required: true
        type: string
        description: release name
      - name: phase
        in: path
        required: true
        type: string
      - in: body
        name: uid
        description: Signoff UID
        required: true
        schema:
          type: string
      responses:
        409:
          description: Already submitted
        200:
          description: Retruns phase signoff representation
          schema:
            $ref: '#/definitions/Signoffs'

  /disabled-products:
    get:
      summary: Get the list of product/branches which are currently disabled. Disabled products/branches will not have automated releases created
      operationId: shipit_api.api.get_disabled_products
      responses:
        200:
          description: Disabled product/branches
          schema:
            type: object
    post:
      summary: Disable a product+branch
      operationId: shipit_api.api.disable_product
      parameters:
      - in: body
        name: body
        description: Disable Product object
        required: true
        schema:
          $ref: '#/definitions/DisableProduct'
      responses:
        200:
          description: OK
        405:
          description: Invalid input
    delete:
      summary: Enable a product+branch
      operationId: shipit_api.api.enable_product
      parameters:
      - name: product
        in: path
        required: true
        type: string
        enum:
        - firefox
        - fennec
        - devedition
        - thunderbird
      - name: branch
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
        405:
          description: Invalid input

definitions:
  ReleaseInput:
    type: object
    required:
    - product
    - version
    - branch
    - revision
    - build_number
    properties:
      product:
        type: string
        example: firefox
        enum:
        - firefox
        - fennec
        - devedition
        - thunderbird
      version:
        type: string
        example: 56.0b12
      branch:
        type: string
        example: projects/maple
      revision:
        type: string
        example: abcd1234
      build_number:
        type: integer
        example: 12
      release_eta:
        type: string
        format: dateTime
        example: 2006-08-14T02:34:56-06:00
      partial_updates:
        type: object
        default: {}
      product_key:
        type: string
        example: fennec_beta

  ReleaseStatus:
    type: object
    required:
      - status
    properties:
      status:
        type: string
        example: scheduled
        enum:
          - scheduled
          - shipped
          - aborted

  Phase:
    type: object
    required:
      - name
      - submitted
    properties:
      name:
        type: string
        example: promote_firefox
        description: Release promotion phase name
      submitted:
        type: boolean
        description: Indicated if the phase was submitted to TC
      actionTaskId:
        type: string
        description: Action Task ID for the phase. This is also the taskGroupId for the tasks created for this phase.
      started:
        type: string
        format: dateTime
        example: 2006-08-14T02:34:56-06:00
      completed:
        type: string
        format: dateTime
        example: 2006-08-14T02:34:56-06:00

  Release:
    type: object
    required:
    - name
    - product
    - version
    - branch
    - revision
    - build_number
    - status
    - phases
    properties:
      name:
        type: string
        example: firefox-69.0b1-build1
      product:
        type: string
        example: firefox
        enum:
        - firefox
        - fennec
        - devedition
        - thunderbird
      version:
        type: string
        example: 56.0b12
      branch:
        type: string
        example: projects/maple
      project:
        type: string
        example: maple
      revision:
        type: string
        example: abcd1234
      build_number:
        type: integer
        example: 12
      release_eta:
        type: string
        format: dateTime
        example: 2006-08-14T02:34:56-06:00
      status:
        type: string
        example: scheduled
        enum:
          - scheduled
          - shipped
          - aborted
      phases:
        type: array
        items:
          $ref: '#/definitions/Phase'
      started:
        type: string
        format: dateTime
        example: 2006-08-14T02:34:56-06:00
      completed:
        type: string
        format: dateTime
        example: 2006-08-14T02:34:56-06:00

  Signoffs:
    type: object
    required:
    - signoffs
    properties:
      signoffs:
        type: array
        items:
          $ref: '#/definitions/Signoff'
      deadline:
        type: string
        format: datetime
        description: Deadline of all signoffs

  Signoff:
    type: object
    required:
      - uid
      - name
      - description
      - permissions
    properties:
      uid:
        type: string
        description: Unique identifier
      name:
        type: string
        description: Human readable signoff name
      description:
        type: string
        description: Human readable explpanation of the signogg
      signed:
        type: boolean
        description: Is the signoff signed off
        default: false
      permissions:
        type: string
        description: Permision required to sign the signoff
      completed_by:
        type: string
        description: Person who signed off (Auth0 ID)
        default: ''
      completed:
        type: string
        format: datetime
        description: Timestamp of the signoff

  DisableProduct:
    type: object
    required:
    - product
    - branch
    properties:
      product:
        type: string
        example: firefox
        enum:
        - firefox
        - fennec
        - devedition
        - thunderbird
      branch:
        type: string
        example: projects/maple
