# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: taskgraph.loader.transform:loader

kind-dependencies:
    - k8s-image

transforms:
    - shipit_taskgraph.transforms.cloudops_deploy:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    dependencies:
        tests-js: tests-frontend-node-14
        tests-api: tests-api-python-38
    project: shipitapi
    image-task-id: {task-reference: "<k8s-image>"}

jobs:
    shipit-admin:
        description: "Push to shipit-admin repository."
        dependencies:
            k8s-image: build-docker-image-shipit-admin
        variant: admin
    shipit-public:
        description: "Push to shipit-public repository."
        dependencies:
            k8s-image: build-docker-image-shipit-public
        variant: public
