# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: taskgraph.loader.transform:loader

transforms:
    - shipit_taskgraph.transforms.docker_push:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    worker-type: b-linux
    worker:
        taskcluster-proxy: true
        docker-image: {in-tree: skopeo}
        max-run-time: 3600
        env:
            IMAGE_URL: {artifact-reference: "<push-image/public/image.tar.zst>"}

jobs:
    shipit-admin:
        description: "Push to shipit-admin repository."
        dependencies:
              push-image: build-docker-image-shipit-admin
              tests: tests-api-python-38
        worker:
            env:
                DOCKER_REPO: docker.io/mozilla/releng-shipit-admin
                DEPLOY_SECRET_URL: http://taskcluster/secrets/v1/secret/project/releng/shipit/deploy
    shipit-public:
        description: "Push to shipit-public repository."
        dependencies:
              push-image: build-docker-image-shipit-public
              tests: tests-api-python-38
        worker:
            env:
                DOCKER_REPO: docker.io/mozilla/releng-shipit-public
                DEPLOY_SECRET_URL: http://taskcluster/secrets/v1/secret/project/releng/shipit/deploy
