#!/usr/bin/env bash

set -o errexit -o pipefail
set -e

export AWS_ACCESS_KEY_ID=$(curl ${DEPLOY_SECRET} | python3 -c "import json, sys; a = json.load(sys.stdin); print(a['secret']['frontend_config']['${RELEASE_CHANNEL}']['aws']['access_key'])")
export AWS_SECRET_ACCESS_KEY=$(curl ${DEPLOY_SECRET} | python3 -c "import json, sys; a = json.load(sys.stdin); print(a['secret']['frontend_config']['${RELEASE_CHANNEL}']['aws']['secret_key'])")

HEADERS=$(cat <<EOF
{ \
    "Content-Security-Policy": "default-src https://auth.mozilla.auth0.com 'none'; img-src 'self' https://*.gravatar.com https://i1.wp.com data:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.auth0.com; style-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; connect-src https://hg.mozilla.org https://auth.mozilla.auth0.com $SHIPIT_API_URL $SHIPIT_PUBLIC_API_URL $FRONTEND_TASKCLUSTER_ROOT_URL; frame-src 'self' https://auth.mozilla.auth0.com; frame-ancestors 'none'; base-uri 'none'; form-action 'none'", \
    "Strict-Transport-Security": "max-age=63072000", \
    "X-Content-Type-Options": "nosniff", \
    "X-Content-Type-Options": "nosniff", \
    "X-XSS-Protection": "1; mode=block", \
    "Referrer-Policy": "no-referrer", \
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains; always;" \
}
EOF
)

yarn build

cp scripts/404.html build/404.html

SYNC_OPTIONS=(
    --metadata "$HEADERS"
    --metadata-directive "REPLACE"
    --cache-control "max-age=300"
    --delete
)
aws s3 sync \
    "${SYNC_OPTIONS[@]}" \
    ./build/ "s3://${WEBSITE_BUCKET}/"
