"""Initial migration.

Revision ID: 3bd3bbb68ca2
Revises:
Create Date: 2026-01-21 12:05:53.442583

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3bd3bbb68ca2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipit_api_disabled_products",
        sa.Column("product", sa.String(), nullable=False),
        sa.Column("branch", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("product", "branch"),
        if_not_exists=True,
    )
    op.create_table(
        "shipit_api_releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("product", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("branch", sa.String(), nullable=False),
        sa.Column("revision", sa.String(), nullable=False),
        sa.Column("build_number", sa.Integer(), nullable=False),
        sa.Column("release_eta", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("completed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        if_not_exists=True,
    )
    op.create_table(
        "shipit_api_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("product_channel", sa.String(), nullable=False),
        sa.Column("current_version", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_name"),
        sa.UniqueConstraint("product_name", "product_channel", name="_product_name_channel_uc"),
        if_not_exists=True,
    )
    op.create_table(
        "shipit_api_xpi_releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("build_number", sa.Integer(), nullable=False),
        sa.Column("xpi_name", sa.String(), nullable=False),
        sa.Column("xpi_revision", sa.String(), nullable=False),
        sa.Column("xpi_version", sa.String(), nullable=False),
        sa.Column("revision", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("completed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        if_not_exists=True,
    )
    op.create_table(
        "shipit_api_phases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("submitted", sa.Boolean(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("completed", sa.DateTime(), nullable=True),
        sa.Column("completed_by", sa.String(), nullable=True),
        sa.Column("release_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["shipit_api_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_table(
        "shipit_api_xpi_phases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("submitted", sa.Boolean(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("completed", sa.DateTime(), nullable=True),
        sa.Column("completed_by", sa.String(), nullable=True),
        sa.Column("release_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["shipit_api_xpi_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_table(
        "shipit_api_signoffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permissions", sa.String(), nullable=False),
        sa.Column("completed", sa.DateTime(), nullable=True),
        sa.Column("completed_by", sa.String(), nullable=True),
        sa.Column("signed", sa.Boolean(), nullable=True),
        sa.Column("phase_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["shipit_api_phases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
        if_not_exists=True,
    )
    op.create_table(
        "shipit_api_xpi_signoffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permissions", sa.String(), nullable=False),
        sa.Column("completed", sa.DateTime(), nullable=True),
        sa.Column("completed_by", sa.String(), nullable=True),
        sa.Column("signed", sa.Boolean(), nullable=True),
        sa.Column("phase_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["shipit_api_xpi_phases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipit_api_xpi_signoffs")
    op.drop_table("shipit_api_signoffs")
    op.drop_table("shipit_api_xpi_phases")
    op.drop_table("shipit_api_phases")
    op.drop_table("shipit_api_xpi_releases")
    op.drop_table("shipit_api_versions")
    op.drop_table("shipit_api_releases")
    op.drop_table("shipit_api_disabled_products")
    # ### end Alembic commands ###
