"""Add merge automation

Revision ID: a91368f8211b
Revises: 3bd3bbb68ca2
Create Date: 2026-01-21 13:53:33.842090

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a91368f8211b"
down_revision = "3bd3bbb68ca2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipit_api_merge_automation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product", sa.String(), nullable=False),
        sa.Column("behavior", sa.String(), nullable=False),
        sa.Column("revision", sa.String(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("completed", sa.DateTime(), nullable=True),
        sa.Column("status", sa.Enum("Pending", "Running", "Failed", "Completed", "Canceled", name="taskstatus"), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True, unique=True),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=True),
        sa.Column("commit_author", sa.String(), nullable=True),
        sa.Column("repo", sa.String(), nullable=False),
        sa.Column("pretty_name", sa.String(), nullable=False),
        sa.Column("project", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipit_api_merge_automation")
    # ### end Alembic commands ###
