ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}

COPY --from=ghcr.io/astral-sh/uv:0.7.9 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml /app/

RUN uv sync --only-group tox

COPY tox.ini /app/

COPY src/ /app/src/

ENTRYPOINT ["/bin/uv", "run", "tox", "-e"]
