ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}

WORKDIR /app

COPY MANIFEST.in setup.py tox.ini /app/
COPY requirements/ /app/requirements/
COPY src/ /app/src/

RUN pip install -r requirements/local.txt

ENTRYPOINT ["/usr/local/bin/tox", "-e"]
