ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}

COPY requirements/poetry.txt /tmp/poetry.txt
RUN pip install -r /tmp/poetry.txt

WORKDIR /app

COPY pyproject.toml /app/

RUN poetry install --only tox --no-root

COPY tox.ini /app/

COPY src/ /app/src/

ENTRYPOINT ["/usr/local/bin/poetry", "run", "tox", "-e"]
