---
android-components:
  legacy: true
  version-class: "mozilla_version.mobile.MobileVersion"
app-services:
  authorized-ldap-groups:
  - releng
  - shipit_app_services
  - shipit_relman
  # Phases per product, ordered
  phases:
  - promote
  - ship
  firefox-ci-trust-domain: app-services
  version-class: "mozilla_version.gecko.GeckoVersion"
devedition:
  phases:
  - promote_devedition
  - push_devedition
  - ship_devedition
  firefox-ci-trust-domain: gecko
  version-class: "mozilla_version.gecko.DeveditionVersion"
fenix:
  legacy: true
  version-class: "mozilla_version.fenix.FenixVersion" # TODO replace with MobileVersion
fennec:
  legacy: true
  version-class: "mozilla_version.gecko.FennecVersion"
firefox:
  phases:
  - promote_firefox
  - push_firefox
  - ship_firefox
  firefox-ci-trust-domain: gecko
  version-class: "mozilla_version.gecko.GeckoVersion"
firefox-android:
  phases:
  - promote
  - push
  - ship
  - promote_android
  - push_android
  - ship_android
  firefox-ci-trust-domain: mobile
  version-class: "mozilla_version.mobile.MobileVersion"
focus-android:
  legacy: true
  version-class: "mozilla_version.mobile.MobileVersion"
mozilla-vpn-addons:
  authorized-ldap-groups:
  - releng
  phases:
  - promote-addons
  - ship-addons
  firefox-ci-trust-domain: mozillavpn
  version-class: "mozilla_version.version.BaseVersion"
mozilla-vpn-client:
  authorized-ldap-groups:
  - releng
  phases:
  - promote-client
  - ship-client
  firefox-ci-trust-domain: mozillavpn
  version-class: "mozilla_version.version.BaseVersion"
thunderbird:
  phases:
  - promote_thunderbird
  - push_thunderbird
  - ship_thunderbird
  firefox-ci-trust-domain: comm
  version-class: "mozilla_version.gecko.ThunderbirdVersion"
